### Ideas
- Lista di mosse disponibili (circa 20 mosse?)
- Codificare gli individui come una sequenza di queste mosse associate a un voto, il voto è relativo a quanto quella mossa lo fa avanzare verso la vittoria. Ad esempio, se passo da 2 a 3 elementi ho un voto positivo. La fitness è data dalla somma di questi pesi, insieme alla lunghezza del genoma.
-  

### minmax alfa-beta
alcune idee da applicare:
- iterative deepening, cioè invece di effettuare una ricorsione un numero di volte pari alla depth, partiamo da 0 e andiamo avanti (1, 2, 3, 4, 5 ...) e decidiamo di stopparci in base a un timeout
- cache table: in una sorta di q-learning, quando apriamo un nodo tanto (tipo depth 5), ci salviamo il risultato cosi, prima di partire, l'algoritmo controlla se è stato già visitato.

In [25]:
import numpy as np

x = [(0,1), (1,5)]

x.zip()

AttributeError: 'list' object has no attribute 'zip'

In [5]:
from game import Game, Move, Player
from minmax import MinMaxPlayer
import random


In [6]:
class RandomPlayer(Player):
    def __init__(self) -> None:
        super().__init__()

    def make_move(self, game: 'Game') -> tuple[tuple[int, int], Move]:
        from_pos = (random.randint(0, 4), random.randint(0, 4))
        move = random.choice([Move.TOP, Move.BOTTOM, Move.LEFT, Move.RIGHT])
        return from_pos, move


In [13]:
g = Game()
g.print()
player1 = MinMaxPlayer(g)
player2 = RandomPlayer()
winner = g.play(player1, player2)
g.print()
print(f"Winner: Player {winner}")


[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


TypeError: 'NoneType' object is not subscriptable